### PR TITLE
Update ja.json

### PR DESCRIPTION
**Pull request by xMasa-1022**
Fixed some japanese translate and grammers.

### CODE REVIEW

**Comment by giorgi-o** [comment]
Thank you! ❤️ 

Do you want to add yourself to the `translation_by` credits on line 2?

**Comment by xMasa-1022** [comment]
Nah, its just a little issue.
don't need, thanks for good applications

**Comment by giorgi-o** [comment]
Did you close it by accident? If it is closed, I can't merge it 😅

**Comment by xMasa-1022** [comment]
😱
sorry, its mistake

**Pull request merged**
